let bitcoinData = {
    "bpi": {
    "EUR": {
        "code": "EUR",
            "description": "Euro",
            "rate": "815.8994",
            "rate_float": 815.8994,
            "symbol": "&euro;"
    },
    "GBP": {
        "code": "GBP",
            "description": "British Pound Sterling",
            "rate": "677.4879",
            "rate_float": 677.4879,
            "symbol": "&pound;"
    },
    "USD": {
        "code": "USD",
            "description": "United States Dollar",
            "rate": "728.4816",
            "rate_float": 728.4816,  // $728 = 1 bitcoin
            "symbol": "&#36;"
    }
},
    "chartName": "Bitcoin",
    "disclaimer": "This data was generated by creating random numbers and mimics the Coinbase API JSON response structure. It is NOT real data. DO NOT USE THIS TO TRADE CRYPTOCURRENCY!",
    "time": {
    "updatedISO": "2023-02-14T20:16:14.370072"
}
}

//tasks:
// Can you convert $100 into Bitcoin?
// Can you print (console.log) the currency descriptions and the rates, one per line?

let bpi = bitcoinData.bpi

for (let currency in bpi) {  //loop over every property in the bpi object
    //console.log(currency)
    let currencyData = bpi[currency] //get the value of that property, an object with the data about one currency
    //console.log(currencyData)
    let currencyDescription = currencyData.description //read values from this object
    let rate = currencyData.rate
    console.log(currencyDescription + " " + rate)
}

console.log(bpi)

let usdData = bpi.USD
console.log(usdData)

let usdExchangeRate = usdData.rate_float  // one bitcoin  equals 728.4816
console.log("One bitcoin is " + usdExchangeRate + " USD")

let oneHundredDollarsInBitcoin = 100 * usdExchangeRate
console.log(oneHundredDollarsInBitcoin)